[package]
name = "lapin"
version = "0.1.0"
edition = "2021"
links = "x11"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
x11rb = {version = "0.11.1", features = ["all-extensions"]}
x11 = "2.21.0"
