[package]
name = "lapin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
x11rb = "0.11.1"
keyfn-closures = "0.2.1"
xkbcommon = "0.5.0"